# -*- coding: utf-8 -*-
"""Movie_Recommendation_System_using_NMF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UJcD-ZDNouF9OcM-72ufhpiW0ih2cNuP

# Movie Recommendation System using NMF(Non-Negative Matrix Factorization), and using TF-IDF Vectorizer

## Importing the necessary requirements (Libraries & Dataset)
"""

# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF
from sklearn.preprocessing import normalize
from sklearn.metrics.pairwise import cosine_similarity

# Downloading our dataset - TMDB dataset
import kagglehub

# Download latest version
path = kagglehub.dataset_download("asaniczka/tmdb-movies-dataset-2023-930k-movies")

print("Path to dataset files:", path)

"""## Data processing"""

# Reading our .csv data into a dataframe
df = pd.read_csv("/kaggle/input/tmdb-movies-dataset-2023-930k-movies/TMDB_movie_dataset_v11.csv")

print(f"Samples in the data: {df.shape[0]}")
print(f"Features in the data: {df.shape[1]}")
print("Column Names:")
print(df.isnull().sum())

# Selecting the features of our data relevant for our use (title,overview,genres)

df = df[["title","overview","genres"]].dropna()

print("The new stats of our data are")
print("="*30)
print(f"Samples in the data: {df.shape[0]}")
print(f"Features in the data: {df.shape[1]}")
print("Column Names:")
print(df.isnull().sum())

# Viewing the first three rows of our data
df.head(3)

"""## Making our TF-IDF matrix from the "overview" feature and building our NMF model

"""

# Making our TF-IDF matrix

tfidf = TfidfVectorizer(
    max_features = 5000,  # Take the 5000 most important words as features
    stop_words = "english", # Words such as 'as','the', 'a' etc are not taken into account
    ngram_range=(1,2), # Include both unigrams and two-word phrases(bigrams) such as 'serial killer', 'outer space' as single features  rather than picking them up as noise
    min_df = 2 # A word must be appear in atleast 2 movies to be included, So that typos and ultra-rare words are excluded.
)

X = tfidf.fit_transform(df["overview"])

print("Matrix shape: ",X.shape)
print("Type: ",type(X))
print("Non-zero entries: ", X.nnz)
print(f"Sparsity: {100* (1-X.nnz/(X.shape[0]*X.shape[1])):.1f}% zeros.")

"""### The ouput of the cell above represents
* (n_movies,n_words) -> (651045,5000)
* X.nnz → number of stored (non-zero) values. Tells you how dense the data is.
* Sparsity → expect 95-99% zeros. This is totally normal for text data.
"""

# Saving our tfidf_matrix
import os
from pathlib import Path
from scipy.sparse import save_npz

os.makedirs(os.path.dirname("data/tfidf_matrix.npz"),exist_ok = True)
save_npz("data/tfidf_matrix.npz",X)

# Exploring the Vocabulary

vocab = tfidf.get_feature_names_out()

# Q1: How many unique words/phrases did TF-IDF learn?
print("Vocabulary size:", len(vocab))

# Q2: Show the first 20 features
print("First 20 features:", vocab[:20])

# Q3: Convert one movie's TF-IDF row to a readable Series and show top 10 words
movie_idx = 0   # ← change this to try different movies
movie_vec = pd.Series(
    X[movie_idx].toarray().flatten(),
    index=vocab
).sort_values(ascending=False)

print(f"\nTop 10 TF-IDF words for '{df['title'].iloc[movie_idx]}':")
print(movie_vec.head(10))

# Now building our NMF model

# Selecting the number of topics to be 20
K = 20

nmf_model = NMF(
    n_components = K,
    init = "nndsvda",# the initialisation strategy. nndsvda uses SVD to make an intelligent first guess at W and H, which leads to faster convergence and better results than random initialisation. This is the recommended setting for sparse TF-IDF data.
    random_state = 42,
    max_iter = 400
)

W =  nmf_model.fit_transform(X)  # movies * topics
H =  nmf_model.components_  # topics * words

print("W shape (movies × topics):", W.shape)
print("H shape (topics × words) :", H.shape)
print(f"Reconstruction error     : {nmf_model.reconstruction_err_:.4f}") # how well W × H approximates X. Lower is better. It's the Frobenius norm of X - W×H

# Inspecting the topics
def print_topics(model, feature_names, n_top_words=10):
    for topic_idx, topic_vec in enumerate(model.components_):
        top_word_indices = topic_vec.argsort()[::-1][:n_top_words]
        top_words = [feature_names[i] for i in top_word_indices]
        print(f"Topic {topic_idx:2d}: {' | '.join(top_words)}")

vocab = tfidf.get_feature_names_out()
print_topics(nmf_model, vocab)

"""## Using the model to make Recommendations- through cosine similarity

The logic
We have W of shape (movies × topics). Each row is a movie's "topic fingerprint" — a vector describing how much of each topic it contains.
To recommend movies similar to a query movie, we:

1. Look up its row in W.
2. Compute how similar that row is to every other row.
3. Return the movies with highest similarity.

We use **cosine similarity** — it measures the angle between two vectors, not their magnitude. This is better than Euclidean distance for text because it's scale-invariant (a long detailed plot vs a short plot won't be penalised for length).
cosine_similarity(A, B) = (A · B) / (||A|| × ||B||)
If we first normalise every row of W to unit length (||row|| = 1), then cosine similarity = dot product, which is faster.

` cosine_similarity(A, B) = (A · B) / (||A|| × ||B||) `
"""

# Making the predictions and thus recommendations

# First we normalize every row of W using L2 norm
W_norm = normalize(W,norm="l2")

# The recommendation function
def recommend(query_title,df,W_norm,top_n = 5):

  # 1.) Find the row index of the query movie in the original dataframe
  matches = df.index[df["title"] == query_title].tolist()

  if not matches:
    print(f"Movie '{query_title}' not found..")
    return

  idx = matches[0]

  # now we compute the cosine similarity of query movie vs all other movies
  query_vec = W_norm[idx].reshape(1,-1)
  sims = cosine_similarity(query_vec,W_norm)[0]

  # Sort similarity in the descending order, skipping the index 0 cause it is the queried movie itself
  ranked = np.argsort(sims)[::-1]
  ranked = [i for i in ranked if i!= idx][:top_n]

  print(f"\n Because you watched: '{query_title}'")
  print(f"   Genre: {df.loc[idx, 'genre'] if 'genre' in df.columns else 'unknown'}")
  print(f"{'─'*50}")
  for rank, movie_idx in enumerate(ranked, 1):
    title  = df["title"].iloc[movie_idx]
    genre  = df["genre"].iloc[movie_idx] if "genre" in df.columns else ""
    score  = sims[movie_idx]
    print(f"  {rank}. {title:<35} sim={score:.3f}  [{genre}]")

# Test it
recommend("Inception", df, W_norm)
recommend("The Godfather", df, W_norm)
recommend("Amélie", df, W_norm)

# Visualizing the movie's topic fingerprint
def plot_topic_profile(query_title, df, W, topic_labels=None):
    idx = df.index[df["title"] == query_title][0]
    profile = W[idx]
    labels  = topic_labels if topic_labels else [f"T{i}" for i in range(len(profile))]

    plt.figure(figsize=(10, 3))
    bars = plt.bar(labels, profile, color="steelblue", edgecolor="white")
    plt.title(f"Topic profile: '{query_title}'")
    plt.ylabel("Topic weight")
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.show()

# Example (replace labels with your own from Exercise 2)
plot_topic_profile("Inception", df, W)
plot_topic_profile("The Godfather", df, W)

